import { Outfit } from "next/font/google";
import "./globals.css";

const outer = Outfit({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-outer",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${outer.className} antialiased`}>{children}</body>
    </html>
  );
}
